=== wavesoftware/glassfish-ant-console/docs/glassfish-console.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="glassfish-console">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="security">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="realm">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="class"/>
                    <xs:element type="xs:string" name="jaas-context"/>
                    <xs:element type="xs:string" name="datasource-jndi"/>
                    <xs:element type="xs:string" name="user-table" nillable="true"/>
                    <xs:element type="xs:string" name="user-name-column" nillable="true"/>
                    <xs:element type="xs:string" name="password-column" nillable="true"/>
                    <xs:element type="xs:string" name="group-table" nillable="true" />
                    <xs:element type="xs:string" name="group-name-column" nillable="true" />
                    <xs:element type="xs:string" name="group-table-user-name-column" nillable="true" />
                    <xs:element type="xs:string" name="digest-algorithm" nillable="true" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== wavesoftware/glassfish-ant-console/src/test/resources/com/github/wavesoftware/glassfish/ant/tasks/glassfish-console.xml
<?xml version="1.0" encoding="UTF-8"?>
<glassfish-console xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="https://raw.github.com/wavesoftware/glassfish-ant-console/master/docs/glassfish-console.xsd">
    <security>
        <realm>
            <name>JDBC_myproject</name>
            <class>com.sun.enterprise.security.ee.auth.realm.jdbc.JDBCRealm</class>
            <jaas-context>jdbcRealm</jaas-context>
            <datasource-jndi>jdbc/MyProject</datasource-jndi>
            <user-table>users</user-table>
            <user-name-column>username</user-name-column>
            <password-column>password</password-column>
            <group-table>groups</group-table>
            <group-name-column>group_name</group-name-column>
            <group-table-user-name-column>username</group-table-user-name-column>
            <digest-algorithm>none</digest-algorithm>
        </realm>
    </security>
</glassfish-console>
